{{- if .Values.gateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gatewayClass.name }}
  namespace: {{ template "annuums-gateway.namespace" . }}
  labels:
    {{- include "annuums-gateway.labels" . | nindent 4 }}
    {{- if .Values.gateway.labels }}
    {{- toYaml .Values.gateway.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.gateway.annotations }}
  annotations:
    {{- toYaml .Values.gateway.annotations | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.name }}
  listeners:
    {{- with .Values.gateway.listeners }}
    {{- range . }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      {{- if .port }}
      port: {{ .port }}
      {{- end }}
      {{- if .allowedRoutes }}
      allowedRoutes:
        namespace:
          from: Selector
          matchLabels:
            {{- toYaml .allowedRoutes.matchLabels | nindent 12 }}
      {{- end }}
      {{- if .tls }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
