{{- if .Values.gatewayClass }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
  namespace: {{ template "annuums-gateway.namespace" . }}
  labels:
    {{- include "annuums-gateway.labels" . | nindent 4 }}
    {{- if .Values.gatewayClass.labels }}
    {{- toYaml .Values.gatewayClass.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.gatewayClass.annotations }}
  annotations:
    {{- toYaml .Values.gatewayClass.annotations | nindent 4 }}
  {{- end }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName }}
{{- end }}
