{{- if .Values.gateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ template "annuums-gateway.namespace" . }}
  labels:
    {{- include "annuums-gateway.labels" . | nindent 4 }}
    {{- if .Values.gateway.labels }}
    {{- toYaml .Values.gateway.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.gateway.annotations }}
  annotations:
    {{- toYaml .Values.gateway.annotations | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    {{- with .Values.gateway.listeners }}
    {{- range . }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      {{- if .hostname }}
      hostname: {{ .hostname }}
      {{- end }}
      {{- if .port }}
      port: {{ .port }}
      {{- end }}
      {{- if .allowedRoutes }}
      allowedRoutes:
        {{- if .allowedRoutes.namespaces }}
        namespaces:
          from: {{ required "allowedRoutes.namespaces.from is required" .allowedRoutes.namespaces.from }}
          {{- if eq .allowedRoutes.namespaces.from "Selector" }}
          selector:
            {{- toYaml (required "allowedRoutes.namespaces.selector is required when from is Selector" .allowedRoutes.namespaces.selector) | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .allowedRoutes.kinds }}
        kinds:
          {{- toYaml .allowedRoutes.kinds | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .tls }}
      tls:
        {{- toYaml .tls | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- if .Values.gateway.addresses }}
  addresses:
    {{- toYaml .Values.gateway.addresses | nindent 4 }}
  {{- end }}
  {{- if .Values.gateway.infrastructure }}
  infrastructure:
    {{- toYaml .Values.gateway.infrastructure | nindent 4 }}
  {{- end }}
{{- end }}
