{{- range .Values.grpcRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ .name }}
  namespace: {{ template "annuums-gateway.namespace" $ }}
  labels:
    {{- include "annuums-gateway.labels" $ | nindent 4 }}
    {{- if .labels }}
    {{- toYaml .labels | nindent 4 }}
    {{- end }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml (required (printf "grpcRoutes[%s].parentRefs is required" .name) .parentRefs) | nindent 4 }}
  {{- if .hostnames }}
  hostnames:
    {{- toYaml .hostnames | nindent 4 }}
  {{- end }}
  rules:
    {{- toYaml (required (printf "grpcRoutes[%s].rules is required" .name) .rules) | nindent 4 }}
{{- end }}
