{{- if .Values.httpRoutes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRoutes.name }}
  namespace: {{ template "annuums-gateway.namespace" . }}
  labels:
    {{- include "annuums-gateway.labels" . | nindent 4 }}
    {{- if .Values.httpRoutes.labels }}
    {{- toYaml .Values.httpRoutes.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.httpRoutes.annotations }}
  annotations:
    {{- toYaml .Values.httpRoutes.annotations | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoutes.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoutes.hostnames | nindent 4 }}
  rules:
    {{- toYaml .Values.httpRoutes.rules | nindent 4 }}
{{- end }}
