fullnameOverride: annuums-gateway
appVersionSuffix: gateway-chart
namespace: annuums-gateway

gatewayClass:
  name: my-gateway-class
  annotations: {}
  labels: {}
  controllerName: my-gateway-controller

gateway:
  className: my-gateway-class
  name: my-gateway
  annotations: {}
  labels: {}
  listeners:
    - name: http
      port: 80
      hostname: example.com
      protocol: HTTP
      allowedRoutes:
        matchLabels:
          app: my-app
          front: react
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate # If protocol is `TLS`, `Passthrough` is a possible mode
        certificateRefs:
          - kind: Secret
            group: ""
            name: default-cert

httpRoutes:
  name: my-http-route
  annotations: {}
  labels: {}
  # You can add multiple parentRefs
  # Usecase: 
  parentRefs:
    - name: my-gateway
    - name: my-gateway-2
  hostnames:
    - example.com
  rules:
    # example.com/foo -> my-service:80
    - matches:
      - path:
          type: PathPrefix
          value: /foo
      backendRefs:
        - name: my-service
          port: 80
    # If you want to fine tune in details, you can add them here
    - filters:
      # http://example.com/foo -> https://example.com/foo
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
    - filters:
        # example.com/foo -> rew.example.com/foo
        - type: URLRewrite
          urlRewrite:
            hostname: rew.example.com
    - filters:
      # example.com/foo -> rew.example.com/bar
      - type: URLRewrite
        urlRewrite:
          hostname: rew.example.com
          path:
            type: ReplaceFullPath
            replaceFullPath: /bar
    - filters:
      # example.com/foo/hello -> rew.example.com/bar/hello
      - type: URLRewrite
        urlRewrite:
          hostname: rew.example.com
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /bar

grpcRoutes:
  name: my-grpc-route
  annotations: {}
  labels: {}
  parentRefs:
    - name: my-gateway
  hostnames:
    - example.com
  rules:
  - matches:
    - headers:
      - type: Exact
        name: env
        value: canary
    backendRefs:
    - name: bar-svc-canary
      port: 50051
  - backendRefs:
    - name: bar-svc
      port: 50051
