fullnameOverride: annuums-gateway
appVersionSuffix: gateway-chart
# namespaceOverride: annuums-gateway

gatewayClass: {}

gateway: {}

httpRoutes: []

grpcRoutes: []

tlsRoutes: []

referenceGrants: []

loadBalancerConfigurations: []

targetGroupConfigurations: []
