{{- $hasHpa := and (hasKey .Values.autoscaling "hpa") (gt (len .Values.autoscaling.hpa) 0) -}}
{{- if and .Values.autoscaling.enabled $hasHpa }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "annuums-deployment.fullname" . }}
  namespace: {{ template "annuums-deployment.namespace" . }}
  labels:
    {{- include "annuums-deployment.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "annuums-deployment.fullname" . }}
  minReplicas: {{ coalesce .Values.autoscaling.hpa.minReplicas .Values.replicas 1 }}
  maxReplicas: {{ coalesce .Values.autoscaling.hpa.maxReplicas (mul .Values.replicas 2) 2 }}
  metrics:
    {{- if .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 60 .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ default 60 .Values.autoscaling.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if and (not .Values.autoscaling.hpa.targetCPUUtilizationPercentage) (not .Values.autoscaling.hpa.targetMemoryUtilizationPercentage) }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    {{- end }}
  {{- if .Values.autoscaling.hpa.behavior }}
  behavior:
    {{- toYaml .Values.autoscaling.hpa.behavior | nindent 4 }}
  {{- else }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Min
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 4
          periodSeconds: 60
    # (옵션) scaleUp도 함께 보수/공격성 조절 가능
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 4
          periodSeconds: 60
  {{- end }}
{{- end }}
