{{- if and (.Values.service) (.Values.service.create) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ template "annuums-deployment.namespace" . }}
  labels:
    annuums.obs/version: {{ template "annuums-deployment.chart" . }}
    {{- include "annuums-deployment.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.service.ports }}
  ports:
  {{- range .}}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      {{- if .appProtocol }}
        appProtocol: {{ .appProtocol }}
      {{- end }}
  {{- end }}
  {{- end }}
  selector:
    annuums.devops/name: {{ template "annuums-deployment.fullname" . }}-selector
{{- end }}
