{{- if and (.Values.targetGroupBinding) (.Values.targetGroupBinding.create) }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: {{ template "annuums-deployment.fullname" . }}
  namespace: {{ template "annuums-deployment.namespace" . }}
spec:
  serviceRef:
    name: {{ .Values.service.name }}
    port: {{ .Values.targetGroupBinding.port }} #K8s Service Port
  targetGroupARN: {{ .Values.targetGroupBinding.arn }} #Target Group ARN
  targetType: {{ default "ip" .Values.targetGroupBinding.type }} #Target Type
{{- end }}
