{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "annuums-config.fullname" . }}-secret
  namespace: {{ template "annuums-config.namespace" . }}
  labels:
    {{- include "annuums-config.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" .type }}
{{- if .Values.secret.data }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
{{- if .Values.secret.stringData }}
stringData:
  {{- toYaml .Values.secret.stringData | nindent 2 }}
{{- end }}
{{- end }}

