fullnameOverride: annuums-cronjob
appVersionSuffix: cronjob-chart
namespace: annuums-cronjob

serviceAccount:
  create: true
  exist: false
  name: pigeon-cron-sa
  annotations:
    iam.gke.io/gcp-service-account: pigeon-sa@annuums.iam.gserviceaccount.com
    another-annotation: hello-world

labels:
  my-label: custom-label
  cronjob: batch-0

imagePullSecrets:
  - name: my-registry-secret
  - name: my-registry-secret-2

cronjob:
  name: pigeon-cron-job
  schedule: "* * * * *"
  backoffLimit: 0
  activeDeadlineSeconds: 600
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  containers:
    - image:
        repository: first-rep
        tag: 1.0.0
        pullPolicy: Never
      labels:
        test-label: "pigeon-1"
        test-label-another: "pigeon-another"
      annotations:
        test-annotatino-second: "pigeon-1-a"
        test-annotatino-first: "pigeon-1-b"
      args:
        - "while true; do sllep 30; done;"
      command:
        - "sh"
        - "-c"
      volumeMounts:
        - name: hostpath-volume
          mountPath: /foo
          subPath: ./foo
          readOnly: true
      # Resource Default
      # cpu: 250m
      # memory: 128Mi
      resources:
        cpu: 250m
        memory: 256Mi

nodeSelector:
  type: applications
  kubernetes.io/architecture: amd64

volumes:
  - name: hostpath-volume
    hostPath:
      path: /host-foo
      # type: Directory | DirectoryOrCreate | File | FileOrCreate | Socket
      type: Directory
  - name: empty-volume
    emptyDir:
      sizeLimit: 500Mi
      path: /empty-foo
  - name: secret-volume
    secretVolume:
      secretName: secr-volume
  - name: configmap-volume
    configMapVolume:
      name: conf-volume
  - name: pvc-volume
    persistentVolumeClaim:
      name: my-pvc-ref-name
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: pink-pigeon
              operator: In
              values:
                - king
                - queen
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - database
        topologyKey: topology.kubernetes.io/zone
        # Only Pods from a given rollout are taken into consideration when calculating pod affinity.
        # If you update the Deployment, the replacement Pods follow their own affinity rules
        # (if there are any defined in the new Pod template)
        matchLabelKeys:
          - pod-template-hash
tolerations:
  - key: my-key
    operator: Equal
    value: true
    effect: NoSchedule

environment:
  env:
    - name: FOO
      value: BAR
  secret:
    - name: sec-env-name
      ref:
        name: secret-name
        key: secret-key
        optional: false
  configmap:
    - name: cm-env-name
      ref:
        name: configmap-name
        key: configmap-key
  envFrom:
    - type: configmap
      configMapRefName: special-config-name
    - type: configmap
      configMapRefName: another-config-name
    - type: secret
      secretRefName: secret-name
    - type: secret
      secretRefName: another-secret-name
