name: Build and Delivery to Docker Hub

on:
  release:
    types:
      - published

## You can add alert logics if you need to notify the team about the release
jobs:
  extract-release-tag:
    runs-on: ubuntu-latest
    outputs:
      chart: ${{ steps.extract_info.outputs.chart }}
      version: ${{ steps.extract_info.outputs.version }}
    steps:
      - name: Extract Release Information
        id: extract_info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}      
          IFS='-' read -r CHART VERSION <<< "$TAG_NAME"
          
          temp_name="$CHART"
          kebab_case_name=$(echo "$temp_name" | sed 's/\([A-Z]\)/-\1/g' | tr '[:upper:]' '[:lower:]')
          chart_name="${kebab_case_name//_/-}"
          
          echo "chart=$chart_name" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Build will be triggered for chart $chart_name and version: $VERSION"

  test-and-delivery:
    runs-on: ubuntu-latest
    environment: dev
    env:
      registry: registry-1.docker.io/annuums
    permissions:
      contents: "read"
      id-token: "write"
    needs:
      - extract-release-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Get Chart Version"
        if: steps.validate_chart.outputs.stop == ''
        id: "get_chart_version"
        uses: mikefarah/yq@master
        with:
          cmd: yq '.version' ${{ needs.extract-release-tag.outputs.chart }}/Chart.yaml

      - name: "Validate Charts"
        id: "validate_chart"
        run: |
          validate_code=0
          if [ "${{ steps.get_chart_version.outputs.result }}" != "${{ needs.extract-release-tag.outputs.version }}" ]; then
            validate_code=2
            echo "Inconsistency Version :: release version (${{ needs.extract-release-tag.outputs.version }}) and actual chart version (${{ steps.get_chart_version.outputs.result }}) is different."
          else 
            helm template ${{ needs.extract-release-tag.outputs.chart }} -f ${{ needs.extract-release-tag.outputs.chart }}/test-values.yaml > /dev/null || echo "stop=1" >> $GITHUB_OUTPUT
          fi
          
          echo "stop=$validate_code" >> $GITHUB_OUTPUT

      - name: "Fail to validate"
        if: steps.validate_chart.outputs.stop != '0'
        run: |
          echo "Workflow stops because fail to validate the chart ${{ needs.extract-release-tag.outputs.chart }}"
          
          exit ${{ steps.validate_chart.outputs.stop }}

      - name: "Package Helm Chart"
        id: "build_helm_chart"
        run: |
          package_result=$(helm package ${{ needs.extract-release-tag.outputs.chart }})
          export HELM_EXPERIMENTAL_OCI=1

          echo "package_name=${package_result##*/}" >> $GITHUB_OUTPUT
          echo "chart_version: ${{ steps.get_chart_version.outputs.result }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Push Helm Chart to Docker Hub"
        run: |
          echo "Login to helm registry ..."
          # helm registry login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ${{ env.registry }}
          echo ${{ secrets.DOCKER_PASSWORD }} | helm registry login registry-1.docker.io -u annuums --password-stdin 
          
          echo "Pushing package ${{ steps.build_helm_chart.outputs.package_name }}..."
          helm push ${{ steps.build_helm_chart.outputs.package_name }} oci://${{ env.registry }}
